<template>
	<div class="Capitulo6">
		
		<h1 class="cap_lei">CAPÍTULO VI – DOS PROCEDIMENTOS FISCALIZATÓRIOS RELATIVOS À ATIVIDADE EDILÍCIA</h1>
	
		<h2 class="secao_lei">Seção I - Verificação da Regularidade da Obra</h2>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 81. </strong>Toda obra, edificação, serviço e equipamento pode, a qualquer tempo, ser vistoriado pela Prefeitura para a verificação do cumprimento das normas estabelecidas neste Código.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 80. </strong>Compete às Prefeituras Regionais, por meio dos seus servidores municipais, regularmente investidos em cargo público e com poderes fiscalizatórios, a fiscalização das disposições estabelecidas no COE e neste decreto, bem como a aplicação das penalidades previstas no Anexo III do COE, quando for o caso. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">Parágrafo único. </strong>Ressalvado o disposto no inciso XI do artigo 5º da Constituição Federal, deverá ser franqueado o imediato e irrestrito acesso ao local objeto de vistoria ao servidor municipal responsável pela fiscalização, desde que devidamente identificado por documento fornecido pela Administração Municipal.<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 82. </strong>Deve ser mantido, no local da obra ou serviço, o documento que comprova o licenciamento da atividade edilícia em execução, sob pena de lavratura de autos de intimação e de multa, nos termos deste Código e legislação pertinente à matéria, ressalvada a situação prevista no art. 14 deste Código.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 81. </strong>Até o término dos trabalhos, deverá ser mantido, no local da obra ou serviço, o documento que comprove o licenciamento da atividade edilícia em execução, sob pena de lavratura de autos de intimação e de multa, nos termos do artigo 83, inciso III, do COE, observado o disposto no artigo 98 do COE e ressalvada a situação prevista no artigo 14 do COE. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">Parágrafo único. </strong>A guarda dos documentos fora do local da obra ou serviço não exclui a aplicação das penalidades previstas neste artigo. </p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 82. </strong>São documentos hábeis à comprovação da regularidade da atividade edilícia em execução: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> Alvará de Execução; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> Alvará de Autorização. </p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 83. </strong>Constatada irregularidade na execução da obra, devem ser adotados os seguintes procedimentos:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>para a obra sem licença expedida pela Prefeitura, ao proprietário ou possuidor, devem ser lavrados, concomitantemente:</p>
		<p class="corpo_lei"><strong class="destaque-lei">a)</strong> auto de multa por execução da obra sem licença;</p>
		<p class="corpo_lei"><strong class="destaque-lei">b)</strong> auto de embargo;</p>
		<p class="corpo_lei"><strong class="destaque-lei">c)</strong> auto de intimação para adotar as providências visando à solução da irregularidade no prazo de 5 (cinco) dias;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>pelo desvirtuamento da licença, ao proprietário ou possuidor e ao responsável técnico pela obra, devem ser lavrados:</p>
		<p class="corpo_lei"><strong class="destaque-lei">a)</strong> auto de intimação para adotar as providências visando à solução da irregularidade no prazo de 5 (cinco) dias e auto de multa por execução da obra com desvirtuamento da licença;</p>
		<p class="corpo_lei"><strong class="destaque-lei">b)</strong> no caso do desatendimento da intimação, auto de embargo e correspondente auto de multa de embargo;</p>
		<p class="corpo_lei"><strong class="destaque-lei">III - </strong>pelo desatendimento de qualquer disposição deste Código, devem ser lavrados:</p>
		<p class="corpo_lei"><strong class="destaque-lei">a)</strong> auto de intimação para adotar as providências visando ao atendimento da disposição deste Código no prazo de 5 (cinco) dias;</p>
		<p class="corpo_lei"><strong class="destaque-lei">b)</strong> auto de multa correspondente à infração.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>Durante o embargo, fica permitida somente a execução dos serviços indispensáveis à eliminação das infrações que o motivaram, observadas as exigências da legislação pertinente à matéria.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>O embargo cessa somente após:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>a eliminação das infrações que o motivaram, em se tratando de obra com licença;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>a expedição de Alvará de Autorização ou Alvará de Execução, em se tratando de obra sem licença.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 83. </strong>Constatada irregularidade na execução da obra, deverão ser adotados os seguintes procedimentos: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> para a obra sem licença expedida pela Prefeitura, ao proprietário ou possuidor, devem ser imediatamente lavrados auto de multa por execução da obra sem licença, auto de embargo e auto de intimação para adotar as providências visando à solução da irregularidade no prazo de 5 (cinco) dias;<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> pelo desvirtuamento da licença, ao proprietário ou possuidor e ao responsável técnico pela obra, devem ser lavrados:</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">a)</strong> imediatamente, auto de intimação para adotar as providências visando à solução da irregularidade no prazo de 5 (cinco) dias e auto de multa por execução da obra com desvirtuamento da licença; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">b)</strong> no caso do desatendimento da intimação, auto de embargo e correspondente auto de multa de embargo; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">III -</strong> pelo desatendimento de qualquer disposição do COE e deste decreto, quando não houver outros procedimentos expressamente estabelecidos, devem ser lavrados, concomitantemente, auto de intimação para adotar as providências visando ao atendimento da disposição do COE e deste decreto no prazo de 5 (cinco) dias e auto de multa correspondente à infração.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Não atendidas às determinações no prazo fixado na intimação, será aplicada nova multa.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>No caso de obra, será caracterizada a reincidência quando a infração disser respeito ao mesmo documento, nos termos do artigo 98 do COE, no que couber.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>Durante o embargo, fica permitida somente a execução dos serviços indispensáveis à eliminação das infrações que o motivaram, observadas as exigências da legislação pertinente à matéria.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 4º </strong>O embargo cessará a pedido do interessado somente após: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> a eliminação das infrações que o motivaram, em se tratando de obra com licença; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> a expedição de Alvará de Autorização ou Alvará de Execução, em se tratando de obra sem licença. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 5º </strong>O pedido de desembargo da obra será analisado pelo Coordenador de Planejamento e Desenvolvimento Urbano, da Prefeitura Regional correspondente ao local da infração, em despacho fundamentado e publicado no DOC. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 6º </strong>O prosseguimento dos trabalhos no imóvel enquanto não deferido o desembargo caracterizará a resistência ao embargo, adotando-se as providências estabelecidas no artigo 84 do COE, competindo ao Prefeito Regional a solicitação de auxílio policial e a requisição de instauração de inquérito policial. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 7º </strong>A modificação física da obra desde a vistoria anterior caracterizará a resistência ao embargo. </p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 84. </strong>A Prefeitura, nos 5 (cinco) dias subsequentes ao embargo, deve vistoriar a obra e, se constatada resistência ao embargo, adotar os seguintes procedimentos:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>aplicar multas diárias, ao proprietário ou ao possuidor e ao responsável técnico pela obra, até a sua paralisação ou até que a regularização da situação seja comunicada ao setor competente e confirmada pela Prefeitura no prazo de 5 (cinco) dias contados da data do protocolo da comunicação;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>caso a aplicação das multas diárias se mostre insuficiente, solicitar auxílio policial bem como providenciar os meios necessários ao imediato cumprimento do embargo, tais como a apreensão de materiais e o desmonte ou lacração de equipamentos e edificações transitórias, lavrando o respectivo auto;</p>
		<p class="corpo_lei"><strong class="destaque-lei">III - </strong>noticiar imediatamente, à autoridade policial, o desrespeito ao embargo, requerendo a instauração de inquérito policial para a apuração da responsabilidade do infrator por crime de desobediência.</p>
		<p class="corpo_lei"><strong class="destaque-lei">Parágrafo único. </strong>Para os fins do disposto neste Código, considera-se resistência ao embargo o prosseguimento dos trabalhos no imóvel sem a eliminação das irregularidades exigidas no auto de intimação.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 85. </strong>Esgotadas todas as providências administrativas para a paralisação da obra, o servidor municipal deve:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>extrair cópia das principais peças do processo administrativo para encaminhamento à Delegacia de Polícia, a fim de instruir o inquérito policial;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>expedir ofícios ao CREA ou CAU com as informações do processo administrativo para a apuração da responsabilidade profissional;</p>
		<p class="corpo_lei"><strong class="destaque-lei">III - </strong>encaminhar o processo original ao setor jurídico para manifestação e posterior encaminhamento ao Departamento Judicial da Procuradoria Geral do Município para as providências de ajuizamento da ação judicial cabível, sem prejuízo da incidência de multas diárias, em processo próprio, caso persistam as irregularidades.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 84. </strong>Esgotadas todas as providências administrativas para a paralisação da obra, o Supervisor de Fiscalização deverá: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> extrair cópia das principais peças do processo administrativo para encaminhamento à Delegacia de Polícia, a fim de instruir o inquérito policial; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> solicitar que o Gabinete da Prefeitura Regional expeça ofícios ao CREA ou CAU com as informações do processo administrativo para a apuração da responsabilidade profissional; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">III -</strong> encaminhar o processo original ao setor jurídico para manifestação e posterior encaminhamento ao Departamento de Defesa do Meio Ambiente e do Patrimônio, da Procuradoria Geral do Município, para as providências de ajuizamento da ação judicial cabível, sem prejuízo da incidência de multas diárias, em processo próprio, caso persistam as irregularidades. </p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 86. </strong>Constatada situação de risco, em vistoria técnica realizada por servidor com competência específica, além das autuações referidas nos arts. 82 a 84 deste Código, deve ser imediatamente lavrado o auto de interdição, seguindo-se, no que couber, os procedimentos previstos na Seção II deste Capítulo.</p>
		<p class="corpo_lei"><strong class="destaque-lei">Parágrafo único. </strong>Na hipótese prevista no “caput” deste artigo, pode ocorrer o levantamento parcial do embargo para o fim específico da execução das medidas necessárias à eliminação do risco, ficando condicionado à apresentação de ART ou RRT relacionando os serviços a serem executados e seu cronograma de execução.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 85. </strong>Mesmo durante o embargo, acaso constatada situação de risco, em vistoria técnica realizada por servidor com competência específica, além das autuações referidas nos artigos 82 a 84 do COE, deve ser imediatamente lavrado o auto de interdição, seguindo-se, no que couber, os procedimentos previstos neste capítulo. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Na hipótese prevista no “caput” deste artigo, poderá ocorrer o levantamento parcial do embargo para o fim específico da execução das medidas necessárias à eliminação do risco, ficando condicionado à apresentação de ART ou RRT relacionando os serviços a serem executados e seu cronograma de execução. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>Eliminado o risco, retorna-se à situação de embargo, o qual somente cessará nas hipóteses estabelecidas no § 4º do artigo 83 deste decreto. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>Quaisquer trabalhos ou serviços que extrapolem o previsto no § 1º deste artigo caracterizarão resistência ao embargo e à interdição, ensejando as penalidades previstas no COE. </p>
		<h2 class="secao_lei">Seção II - Da Verificação da Estabilidade, Segurança e Salubridade da Obra</h2>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 87. </strong>Verificada a inexistência de condições de estabilidade, segurança ou salubridade de uma obra, edificação, serviço ou equipamento, o proprietário ou o possuidor e o responsável técnico pela obra devem ser intimados a dar início às medidas necessárias à solução da irregularidade no prazo de 5 (cinco) dias, devendo ainda ser lavrado o auto de interdição total ou parcial do imóvel, dando-se ciência aos proprietários e ocupantes.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>No caso de a irregularidade constatada apresentar perigo de ruína ou contaminação, ocorrerá, se necessário, a interdição do entorno do imóvel.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>O não cumprimento da intimação para a regularização necessária ou interdição implica responsabilidade exclusiva do infrator, eximindo-se a Prefeitura da responsabilidade pelos danos decorrentes de eventual sinistro.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 3º </strong>Durante a interdição, fica permitida somente a execução dos serviços indispensáveis à eliminação da irregularidade constatada.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 86. </strong>Verificada a inexistência de condições de estabilidade, segurança ou salubridade de uma obra, edificação, serviço ou equipamento, o proprietário ou o possuidor e o responsável técnico pela obra devem ser intimados a dar início às medidas necessárias à solução da irregularidade no prazo de 5 (cinco) dias, devendo ainda ser lavrado o auto de interdição total ou parcial do imóvel, dando-se ciência aos proprietários e ocupantes.<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Compete aos servidores técnicos municipais, com formação específica, lotados nas Prefeituras Regionais vistoriar e avaliar edificações, obras serviços ou equipamentos com respeito às suas condições de estabilidade, segurança e ou salubridade e determinar a adoção das medidas pertinentes.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>Compete aos servidores municipais, investidos em cargo público e com poderes fiscalizatórios, lotados nas Prefeituras Regionais, lavrar os autos de interdição e de intimação, colher as assinaturas, tanto do técnico que avaliou a situação de risco e determinou a interdição, como do proprietário ou possuidor a qualquer título ou dos ocupantes do local a ser interditado, ou, ainda, atestar a impossibilidade ou recusa.<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>Do auto de interdição necessariamente deverão constar as assinaturas do técnico responsável pela vistoria que ensejou a interdição e do agente público municipal com poderes de fiscalização. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 4º </strong>No caso de a irregularidade constatada apresentar perigo de ruína ou contaminação, ocorrerá, se necessário, a interdição do entorno do imóvel. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 5º </strong>O não cumprimento da intimação para a regularização necessária ou interdição implica responsabilidade exclusiva do infrator, eximindo-se a Prefeitura da responsabilidade pelos danos decorrentes de eventual sinistro. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 6º </strong>Durante a interdição, fica permitida somente a execução dos serviços indispensáveis à eliminação da irregularidade constatada. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 7º </strong>Em se tratando de edificação erigida em imóvel público municipal, cuja ocupação seja clandestina, além da interdição total ou parcial, a intimação prevista neste artigo deverá determinar a desocupação da área pública municipal, conforme legislação municipal pertinente. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 8º </strong>A pedido do interessado, o imóvel poderá ser desinterditado, sendo competência do Coordenador de Planejamento e Desenvolvimento Urbano, da Prefeitura Regional do local da infração, a sua análise, em despacho fundamentado e publicado no DOC.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 88. </strong>Decorrido o prazo concedido, a Prefeitura deve adotar as seguintes medidas:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>pelo desatendimento da intimação, aplicar multas diárias ao infrator até que sejam adotadas as medidas exigidas;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>verificada a desobediência à interdição:</p>
		<p class="corpo_lei"><strong class="destaque-lei">a)</strong> solicitar auxílio policial para o imediato cumprimento da interdição, lavrando o respectivo auto;</p>
		<p class="corpo_lei"><strong class="destaque-lei">b)</strong> noticiar imediatamente, à autoridade policial, o desrespeito à interdição, requerendo a instauração de inquérito policial para a apuração da responsabilidade do infrator por crime de desobediência;</p>
		<p class="corpo_lei"><strong class="destaque-lei">c)</strong> encaminhar o processo para as providências de ajuizamento da ação judicial cabível, sem prejuízo da incidência de multas diárias caso persista o desatendimento da intimação prevista no inciso I deste artigo.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 87. </strong>Decorrido o prazo concedido, a Prefeitura deverá adotar as seguintes medidas:<strong class="destaque-decreto"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> pelo desatendimento da intimação, aplicar multas diárias ao infrator até que sejam adotadas as medidas exigidas; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> verificada a desobediência à interdição:</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">a)</strong> solicitar auxílio policial para o imediato cumprimento da interdição, lavrando o respectivo auto;</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">b)</strong> noticiar imediatamente, à autoridade policial, o desrespeito à interdição, requerendo a instauração de inquérito policial para a apuração da responsabilidade do infrator por crime de desobediência;</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">c)</strong> encaminhar o processo para as providências de ajuizamento da ação judicial cabível, sem prejuízo da incidência de multas diárias caso persista o desatendimento da intimação prevista no “caput” do artigo 86 deste decreto. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">III -</strong> em se tratando de edificação erigida em imóvel público municipal, cuja ocupação seja clandestina, instruir processo com o auto de intimação, auto de interdição e o relatório de vistoria, encaminhando para as providências previstas na legislação municipal pertinente.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 89. </strong>O atendimento da intimação não desobriga o proprietário ou possuidor e o responsável técnico pela obra do cumprimento das formalidades necessárias à regularização da obra, sob pena de aplicação das sanções cabíveis.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 90. </strong>O proprietário ou possuidor do imóvel que constatar perigo de ruína ou contaminação pode, devidamente assistido por profissional habilitado, dar início imediato às obras de emergência, comunicando o fato, por escrito, à Prefeitura e justificando e informando a natureza dos serviços a serem executados, observadas as exigências da legislação pertinente à matéria.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 88. </strong>O proprietário ou possuidor do imóvel que constatar perigo de ruína ou contaminação pode, devidamente assistido por profissional habilitado, dar início imediato às obras de emergência, comunicando o fato, por escrito, à Prefeitura Regional competente, justificando e informando a natureza dos serviços a serem executados, observadas as exigências da legislação pertinente à matéria. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">Parágrafo único. </strong>Quando estiver implementado o sistema informatizado, a comunicação digital suprirá, para todos os fins, a prevista no “caput” deste artigo. </p>
		<h2 class="secao_lei">Seção III - Das Penalidades</h2>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 91. </strong>A inobservância de qualquer disposição deste Código constitui infração sujeita à aplicação das penalidades previstas na Tabela de Multas constante do seu Anexo III.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 89. </strong>A inobservância de qualquer disposição do COE constitui infração sujeita à aplicação das penalidades previstas na Tabela de Multas, constante do seu Anexo III e do Anexo III deste decreto, e ensejará os procedimentos fiscais previstos neste capítulo.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 90. </strong>Os autos previstos no COE e neste decreto, quando a infração exigir lavraturas concomitantes, poderão ser lavrados em um único documento, quando emitidos por meio eletrônico.<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 92. </strong>As penalidades previstas por desrespeito às normas deste Código aplicam-se também em relação a imóveis de valor cultural, histórico, artístico, paisagístico ou ambiental preservados ou a serem preservados e, ainda, a imóveis que, em razão do seu gabarito de altura e recuos, sejam necessários à preservação da volumetria do entorno, sem prejuízo da incidência das penalidades previstas em legislação própria.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 93. </strong>A edificação concluída sem a obtenção de Certificado de Conclusão enseja a intimação do infrator para, no prazo de 5 (cinco) dias, solicitar o documento à Prefeitura, sob pena de lavratura do correspondente auto de multa.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>O pedido de Certificado de Conclusão suspende a ação fiscalizatória até a emissão desse documento ou o indeferimento do pedido, o que ocorrer primeiro.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>A multa será reaplicada a cada 90 (noventa) dias até a regularização da edificação, limitado esse período a 1 (um) ano.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 91. </strong>A edificação concluída sem a obtenção de Certificado de Conclusão enseja a intimação do infrator para, no prazo de 5 (cinco) dias, solicitar o documento à Prefeitura, sob pena de lavratura do correspondente auto de multa.<strong class="destaque-decreto"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Não atendida a intimação ou indeferido o pedido, será aplicada a multa correspondente. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>A multa será reaplicada a cada 90 (noventa) dias até a regularização da edificação, limitado esse período a 1 (um) ano. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>A multa a que se refere o “caput” deste artigo independe do uso da edificação. § </p>
		<p class="corpo_decreto">4º O pedido de Certificado de Conclusão suspende a ação fiscalizatória até a emissão desse documento ou o indeferimento do pedido, o que ocorrer primeiro.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 94. </strong>A edificação concluída sem a obtenção de Certificado de Acessibilidade e de Certificado de Segurança enseja a intimação do infrator para, no prazo de 5 (cinco) dias, solicitar o documento à Prefeitura, sob pena de lavratura do correspondente auto de multa.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>O pedido de Certificado de Acessibilidade ou de Certificado de Segurança suspende a ação fiscalizatória até a emissão desse documento ou o indeferimento do pedido, o que ocorrer primeiro.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>A multa será reaplicada a cada 90 (noventa) dias até a regularização da edificação, limitado esse período a 1 (um) ano.<strong class="destaque-decreto"></strong></p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 92. </strong>A edificação concluída sem a obtenção de Certificado de Acessibilidade e de Certificado de Segurança enseja a intimação do infrator para, no prazo de 5 (cinco) dias, solicitar o documento à Prefeitura, sob pena de lavratura do correspondente auto de multa.<strong class="destaque-decreto"></strong></p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Não atendida a intimação ou indeferido o pedido, será aplicada a multa correspondente.</p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>A multa será reaplicada a cada 90 (noventa) dias até a regularização da edificação, limitado esse período a 1 (um) ano. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>O pedido de Certificado de Acessibilidade ou de Certificado de Segurança suspende a ação fiscalizatória até a emissão desse documento ou o indeferimento do pedido, o que ocorrer primeiro. </p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 93. </strong>Para os imóveis que não apresentarem ligação de esgoto, conforme disposto no item 3.E do Anexo I deste decreto, situados em vias providas de rede coletora, as Prefeituras Regionais deverão, concomitantemente: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> aplicar a multa prevista na Tabela de Multas, contida no Anexo III do COE, correspondente ao valor fixado para as demais infrações das disposições do COE; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> intimar os proprietários ou possuidores a qualquer título das edificações, para que no prazo de 30 (trinta) dias, executem as adaptações necessárias em sua edificação, de modo a possibilitar a ligação do esgoto à rede coletora pública pela concessionária, atendendo as exigências previstas na legislação municipal pertinente, e para que requeira à concessionária de serviços públicos de coleta, tratamento e destinação final de esgoto a execução da ligação de esgoto à rede coletora pública, devendo apresentar, na Prefeitura Regional de sua jurisdição, o protocolo do respectivo pedido. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">Parágrafo único. </strong>Não atendida a intimação no prazo fixado, as Prefeituras Regionais deverão reaplicar a multa a cada período de 30 (trinta) dias, até a apresentação do respectivo protocolo. </p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 94. </strong>Verificado o desrespeito ao estabelecido no subitem 3.4.2 do item 3 do Anexo I do COE, a Prefeitura Regional competente deverá: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> aplicar a multa prevista na Tabela de Multas, contida no Anexo III do COE, correspondente ao valor fixado para as demais infrações das disposições do COE; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> intimar os proprietários ou possuidores a qualquer título das edificações, para que no prazo de 30 (trinta) dias, executem as adaptações necessárias em sua edificação, ou de modo a possibilitar a canalização sob o passeio à rede coletora de águas pluviais, de acordo com as normas emanadas do órgão competente. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">Parágrafo único. </strong>Não atendida a intimação no prazo fixado, as Prefeituras Regionais deverão reaplicar a multa a cada período de 30 (trinta) dias, até que sejam tomadas as medidas necessárias para o saneamento da irregularidade.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 95. </strong>Para os efeitos deste Código, considera-se infrator o proprietário ou possuidor do imóvel e, quando for o caso, o responsável técnico pela obra.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>O infrator deve ser notificado pessoalmente ou por via postal, com aviso de recebimento, ou, ainda, por edital nas hipóteses de recusa do recebimento da notificação ou de sua não localização.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>O infrator considera-se notificado quando encaminhada a notificação por via postal ao endereço constante do cadastro da Municipalidade.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 3º </strong>Quando prevista a aplicação de multa ao proprietário ou possuidor e ao responsável técnico pela obra, a responsabilidade é solidária, considerando-se ambos os infratores.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 4º </strong>Os sucessores do proprietário ou do possuidor do imóvel também respondem pelas penalidades.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 96. </strong>Contra os atos de fiscalização previstos neste Código, cabe defesa ao Supervisor Técnico de Fiscalização, da Subprefeitura, no prazo de 15 (quinze) dias, contados:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>para a intimação e o embargo, a partir da data da respectiva notificação;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>para a multa, a partir da data de sua publicação no Diário Oficial da Cidade.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 1º </strong>Contra o despacho decisório que desacolher a defesa, caberá um único recurso, ao Subprefeito, no prazo de 15 (quinze) dias contados da data da publicação do despacho.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 2º </strong>As defesas e recursos suspendem a exigibilidade dos autos de multa impugnados.</p>
		<p class="corpo_lei"><strong class="destaque-lei">§ 3º </strong>A defesa contra o auto de embargo não suspende a ação fiscalizatória e não obsta a aplicação de outras multas previstas neste Código.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 95. </strong>Contra os atos de fiscalização previstos no COE e neste decreto, cabe defesa ao Supervisor Técnico de Fiscalização, da Prefeitura Regional, no prazo de 15 (quinze) dias, contados: </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">I -</strong> para a intimação e o embargo, a partir da data da respectiva notificação; </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">II -</strong> para a multa, a partir da data de sua publicação no DOC. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 1º </strong>Contra o despacho decisório que desacolher a defesa, caberá um único recurso, ao Prefeito Regional, no prazo de 15 (quinze) dias contados da data da publicação do despacho. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 2º </strong>As defesas e recursos suspendem a exigibilidade dos autos de multa impugnados. </p>
		<p class="corpo_decreto"><strong class="destaque-decreto">§ 3º </strong>A defesa contra o auto de embargo e/ou auto de intimação não suspende a ação fiscalizatória e não obsta a aplicação de outras multas previstas no COE e neste decreto. </p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 97. </strong>Ao proprietário ou possuidor devem ser aplicadas multas nos valores indicados na Tabela de Multas e, ao responsável técnico pela obra, multas na proporção de 80% (oitenta por cento) dos referidos valores.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 98. </strong>A reincidência da infração, assim considerada a referente à mesma obra e ao mesmo documento, gera a aplicação das penalidades com acréscimo de 20% (vinte por cento) a cada reincidência, até o limite de 2 (duas) vezes o valor da multa inicial.</p>
		<p class="corpo_decreto"><strong class="artigo-decreto">Art. 96. </strong>A reincidência da infração, assim considerada a referente à mesma obra e ao mesmo documento, gera a aplicação das penalidades com acréscimo de 20% (vinte por cento) a cada reincidência, até atingir 2 (duas) vezes o valor da multa inicial, depois do que será reaplicada sem novos acréscimos.<strong class="subtitulo_txt"></strong></p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 99. </strong>Para a aplicação dos dispositivos deste Capítulo, os prazos devem ser dilatados até o triplo dos prazos previstos e reduzidos os valores das multas em 90% (noventa por cento) dos valores devidos para:</p>
		<p class="corpo_lei"><strong class="destaque-lei">I - </strong>as moradias econômicas;</p>
		<p class="corpo_lei"><strong class="destaque-lei">II - </strong>os templos religiosos.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 100. </strong>O valor da multa deve ser atualizado anualmente em 1º de fevereiro, pela variação do IPCA, apurado pelo IBGE, ou por outro índice que venha a substituí-lo, verificada entre janeiro e dezembro do exercício anterior.</p>
		<p class="corpo_lei"><strong class="artigo-lei">Art. 101. </strong>Quando não paga até a data do vencimento, o valor da multa deve ser atualizado da forma e pelo índice de correção estabelecidos na Lei nº 10.734, de 1989, com a redação dada pela Lei nº 13.275, de 2002, e acrescido de juros moratórios calculados à taxa de 0,33% (trinta e três centésimos por cento), por dia de atraso, sobre o valor do débito, até o limite de 20% (vinte por cento), sem prejuízo, quando for o caso, do acréscimo de honorários advocatícios, custas e demais despesas judiciais, conforme a legislação municipal pertinente.</p>

	</div>
</template>

<script>
export default{
	name: "Capitulo6", 
	props:['caminho']
}
</script>

<style lang="scss">
@import '../assets/main.scss';
</style>